/-
================================================================================
  WeldAndArrow.Consequences.Taxonomy
  Error taxonomy, table order, and witnesses
================================================================================

Reading and motivation: Identification/Commentary.lean, C.2.
-/

import WeldAndArrow.Consequences.Basic

namespace WAA

namespace Grid

variable {Contrib : Type} [PreorderBot Contrib]
variable (G : Grid Contrib)

namespace DirectedConvention
namespace BeingConvention
namespace GridConvention

/- The lens's own vocabulary: the innermost convention. The abstract
   `ClaimLanguage` machinery remains at `Grid` level; this namespace supplies
   the concrete rows generated from it. -/

/-- The nested conventions as objects the lens can diagnose claims about. -/
inductive ConventionLayer
  | directedTime
  | beings
  | gridLens

/-- Claims for convention-layer rows. `conventionLive l` says the layer's
    distinction is in force; `layerDenied l` is the deflation. -/
inductive LayerClaim
  | conventionLive (l : ConventionLayer)
  | layerDenied (l : ConventionLayer)

/-- Every schema-generated row of the Grade-1 table, as inspectable data. The
    three convention layers embed via `layer`; the level-n row is generated by
    `ladder` instead. -/
inductive RowTag
  | layer (l : ConventionLayer)
  | foxWeld
  | rungPole
  | functionShare
  | karmaInga
  | sowingReaping
  | deliveryIndex
  | weldEventType
  | standingDated
  | subjectObjectAxis
  | undefinedZero
  | perCallGlobal
  | terminusExit
  | selfPoleTransposed

/-- The two sides of a schema-generated row. `inForce r` is the conventional
    side; `denied r` is the floor-side deflation offered as diagnosis. -/
inductive RowClaim
  | inForce (r : RowTag)
  | denied (r : RowTag)

/-- Pole-affirming semantics. The conventional side is true at every act-time;
    the denial side is true at act-time exactly at the pole-class. Thus a
    pole-class act-time validates both sides by truth, not vacuity. -/
def rowLanguage (G : Grid Contrib) : ClaimLanguage G where
  Claim := RowClaim
  Holds
    | .floor, _ => True
    | .actTime _, .inForce _ => True
    | .actTime w, .denied _ => AtBot (G.share w)

def rowOf (G : Grid Contrib) (r : RowTag) : Distinction G :=
  { language := rowLanguage G
    sideA := .inForce r
    sideB := .denied r }

theorem rowOf_separated_at_live
    (r : RowTag) (t : Tier G) (ht : Tier.hasLiveShare G t) :
    (rowOf G r).Separated t := by
  constructor
  · exact ht
  · cases t with
    | floor =>
        cases ht
    | actTime w =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        intro hiff
        exact ht (hiff.mp True.intro)

theorem rowOf_collapse_self_refuting
    (r : RowTag) (t : Tier G) :
    ¬ (rowOf G r).Collapse t := by
  intro hcollapse
  exact (rowOf_separated_at_live G r t hcollapse.left).right hcollapse.right

theorem rowOf_not_freeze (r : RowTag) :
    ¬ (rowOf G r).Freeze := by
  intro hfreeze
  apply hfreeze
  dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
  constructor <;> intro _ <;> exact True.intro

/-- The denial side can be true only where the offered tier is not live. -/
theorem denied_holds_only_where_no_live_share
    (r : RowTag) (t : Tier G)
    (h : (rowLanguage G).Holds t (.denied r)) :
    ¬ Tier.hasLiveShare G t := by
  cases t with
  | floor =>
      intro hfloor
      exact hfloor
  | actTime _ =>
      intro hLive
      exact hLive h

theorem rowOf_errorFree (r : RowTag) :
    ErrorFree G (rowOf G r) :=
  ⟨rowOf_collapse_self_refuting G r, rowOf_not_freeze G r⟩

theorem rowOf_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (r : RowTag) :
    (rowOf G r).ObeysSeparateFuse := by
  constructor
  · intro t hLive
    exact (rowOf_separated_at_live G r t hLive).right
  · intro t hNotLive
    cases t with
    | floor =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        constructor <;> intro _ <;> exact True.intro
    | actTime w =>
        dsimp [rowOf, rowLanguage, ClaimLanguage.TrueAt]
        have hbot : AtBot (G.share w) := by
          by_cases h : AtBot (G.share w)
          · exact h
          · exact False.elim (hNotLive h)
        constructor
        · intro _h
          exact hbot
        · intro _h
          exact True.intro

/-- For the pole-affirming row language, the refutation-only reading and full
    separate/fuse obedience coincide under the local decidability needed to
    turn `¬¬ AtBot` into `AtBot` at non-live act-times. This is not a generic
    theorem about arbitrary distinctions; the satori clause is the load-bearing
    premise. -/
theorem rowOf_obeys_iff_errorFree
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (r : RowTag) :
    (rowOf G r).ObeysSeparateFuse ↔ ErrorFree G (rowOf G r) :=
  ⟨Grid.errorFree_of_obeys G, fun _h => rowOf_obeys G r⟩

/-- At a pole-class act-time every schema-row claim is true there. This is
    truth at that weld and tier, not the pole as a truth-maker elsewhere. -/
theorem pole_validates_all_claims
    {w : G.Weld} (h : AtBot (G.share w)) :
    ∀ p, (rowLanguage G).Holds (Tier.actTime w) p := by
  intro p
  cases p with
  | inForce _ =>
      exact True.intro
  | denied _ =>
      exact h

/-- A live act-time refutes the denial side and the bare equivalence of the two
    sides. The conventional `inForce` side still stands. -/
theorem live_tier_refutes_denials_and_fusions
    (r : RowTag) (t : Tier G) (hLive : Tier.hasLiveShare G t) :
    (¬ (rowLanguage G).Holds t (.denied r)) ∧
      ¬ ((rowLanguage G).Holds t (.inForce r) ↔
        (rowLanguage G).Holds t (.denied r)) := by
  constructor
  · intro hdenied
    exact denied_holds_only_where_no_live_share G r t hdenied hLive
  · exact (rowOf_separated_at_live G r t hLive).right

/-- A denial offered at a live tier does not fit that offered tier. -/
theorem denied_misfits_live_offer
    (r : RowTag)
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied r)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    ¬ RecordedUtterance.FitsOfferedTier u := by
  intro hfit
  change (rowLanguage G).TrueAt u.offeredAt u.content at hfit
  cases hoff : u.offeredAt with
  | floor =>
      rw [hoff] at hlive
      cases hlive
  | actTime w =>
      rw [hoff, hcontent] at hfit
      dsimp [rowLanguage, ClaimLanguage.TrueAt] at hfit
      rw [hoff] at hlive
      exact hlive hfit

abbrev layerRow (G : Grid Contrib) (l : ConventionLayer) : Distinction G :=
  rowOf G (.layer l)

abbrev beforeAfterRow (G : Grid Contrib) : Distinction G :=
  rowOf G (.layer .directedTime)

abbrev beingsRow (G : Grid Contrib) : Distinction G :=
  rowOf G (.layer .beings)

abbrev gridLensRow (G : Grid Contrib) : Distinction G :=
  rowOf G (.layer .gridLens)

theorem layerRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))]
    (l : ConventionLayer) :
    (layerRow G l).ObeysSeparateFuse :=
  rowOf_obeys G (.layer l)

theorem beforeAfterRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (beforeAfterRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .directedTime)

theorem beingsRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (beingsRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .beings)

theorem gridLensRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (gridLensRow G).ObeysSeparateFuse :=
  rowOf_obeys G (.layer .gridLens)

/-- Compatibility name for the migrated layer denials. -/
theorem layerDenied_holds_only_where_no_live_share
    (l : ConventionLayer) (t : Tier G)
    (h : (rowLanguage G).Holds t (.denied (.layer l))) :
    ¬ Tier.hasLiveShare G t :=
  denied_holds_only_where_no_live_share G (.layer l) t h

theorem beforeAfterRow_not_freeze :
    ¬ (beforeAfterRow G).Freeze :=
  rowOf_not_freeze G (.layer .directedTime)

/-- The before/after collapse is self-refuting at every tier; in particular,
    it cannot be asserted as a live diagnosis. -/
theorem no_time_collapse_self_refuting (t : Tier G) :
    ¬ (beforeAfterRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .directedTime) t

/-- The beings row cannot freeze. The freeze cell in the prose table names the
    position this checked row rules out asserting: designation reified into
    ontology against `BeingNegative`. -/
theorem beingsRow_not_freeze :
    ¬ (beingsRow G).Freeze :=
  rowOf_not_freeze G (.layer .beings)

/-- "There are no beings", offered as a live diagnosis, is refuted by its own
    tier. -/
theorem no_beings_collapse_self_refuting (t : Tier G) :
    ¬ (beingsRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .beings) t

theorem gridLensRow_not_freeze :
    ¬ (gridLensRow G).Freeze :=
  rowOf_not_freeze G (.layer .gridLens)

theorem lens_denial_collapse_self_refuting (t : Tier G) :
    ¬ (gridLensRow G).Collapse t :=
  rowOf_collapse_self_refuting G (.layer .gridLens) t

abbrev rungPoleRow (G : Grid Contrib) : Distinction G :=
  rowOf G .rungPole

theorem rungPoleRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (rungPoleRow G).ObeysSeparateFuse :=
  rowOf_obeys G .rungPole

theorem rungPoleRow_not_freeze :
    ¬ (rungPoleRow G).Freeze :=
  rowOf_not_freeze G .rungPole

/-- Kensho read as genjo collapses a rung into the pole. -/
theorem kensho_as_genjo_collapse_self_refuting (t : Tier G) :
    ¬ (rungPoleRow G).Collapse t :=
  rowOf_collapse_self_refuting G .rungPole t

abbrev foxWeldRow (G : Grid Contrib) : Distinction G :=
  rowOf G .foxWeld

theorem foxWeldRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (foxWeldRow G).ObeysSeparateFuse :=
  rowOf_obeys G .foxWeld

theorem foxWeldRow_not_freeze :
    ¬ (foxWeldRow G).Freeze :=
  rowOf_not_freeze G .foxWeld

/-- The fox's "not-fall" side, offered as live diagnosis, is self-refuting. -/
theorem fox_notFall_collapse_self_refuting (t : Tier G) :
    ¬ (foxWeldRow G).Collapse t :=
  rowOf_collapse_self_refuting G .foxWeld t

/-- "Not-fall", offered where diagnosis is live, does not fit its offered
    tier: Case 2 checked against the schema row itself. -/
theorem fox_utterance_misfits_live_offer
    (u : RecordedUtterance G (rowLanguage G))
    (hcontent : u.content = .denied .foxWeld)
    (hlive : Tier.hasLiveShare G u.offeredAt) :
    ¬ RecordedUtterance.FitsOfferedTier u :=
  denied_misfits_live_offer G .foxWeld u hcontent hlive

abbrev functionShareRow (G : Grid Contrib) : Distinction G :=
  rowOf G .functionShare

theorem functionShareRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (functionShareRow G).ObeysSeparateFuse :=
  rowOf_obeys G .functionShare

theorem functionShareRow_not_freeze :
    ¬ (functionShareRow G).Freeze :=
  rowOf_not_freeze G .functionShare

theorem functionZero_from_shareZero_collapse_self_refuting (t : Tier G) :
    ¬ (functionShareRow G).Collapse t :=
  rowOf_collapse_self_refuting G .functionShare t

abbrev karmaIngaRow (G : Grid Contrib) : Distinction G :=
  rowOf G .karmaInga

theorem karmaIngaRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (karmaIngaRow G).ObeysSeparateFuse :=
  rowOf_obeys G .karmaInga

theorem karmaIngaRow_not_freeze :
    ¬ (karmaIngaRow G).Freeze :=
  rowOf_not_freeze G .karmaInga

theorem misfeed_collapse_self_refuting (t : Tier G) :
    ¬ (karmaIngaRow G).Collapse t :=
  rowOf_collapse_self_refuting G .karmaInga t

abbrev sowingReapingRow (G : Grid Contrib) : Distinction G :=
  rowOf G .sowingReaping

theorem sowingReapingRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (sowingReapingRow G).ObeysSeparateFuse :=
  rowOf_obeys G .sowingReaping

theorem sowingReapingRow_not_freeze :
    ¬ (sowingReapingRow G).Freeze :=
  rowOf_not_freeze G .sowingReaping

theorem series_ownership_collapse_self_refuting (t : Tier G) :
    ¬ (sowingReapingRow G).Collapse t :=
  rowOf_collapse_self_refuting G .sowingReaping t

abbrev deliveryIndexRow (G : Grid Contrib) : Distinction G :=
  rowOf G .deliveryIndex

theorem deliveryIndexRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (deliveryIndexRow G).ObeysSeparateFuse :=
  rowOf_obeys G .deliveryIndex

theorem deliveryIndexRow_not_freeze :
    ¬ (deliveryIndexRow G).Freeze :=
  rowOf_not_freeze G .deliveryIndex

theorem misfed_register_collapse_self_refuting (t : Tier G) :
    ¬ (deliveryIndexRow G).Collapse t :=
  rowOf_collapse_self_refuting G .deliveryIndex t

abbrev weldEventTypeRow (G : Grid Contrib) : Distinction G :=
  rowOf G .weldEventType

theorem weldEventTypeRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (weldEventTypeRow G).ObeysSeparateFuse :=
  rowOf_obeys G .weldEventType

theorem weldEventTypeRow_not_freeze :
    ¬ (weldEventTypeRow G).Freeze :=
  rowOf_not_freeze G .weldEventType

theorem eventType_grading_collapse_self_refuting (t : Tier G) :
    ¬ (weldEventTypeRow G).Collapse t :=
  rowOf_collapse_self_refuting G .weldEventType t

abbrev standingDatedRow (G : Grid Contrib) : Distinction G :=
  rowOf G .standingDated

theorem standingDatedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (standingDatedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .standingDated

theorem standingDatedRow_not_freeze :
    ¬ (standingDatedRow G).Freeze :=
  rowOf_not_freeze G .standingDated

theorem prognosis_as_diagnosis_collapse_self_refuting (t : Tier G) :
    ¬ (standingDatedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .standingDated t

abbrev subjectObjectAxisRow (G : Grid Contrib) : Distinction G :=
  rowOf G .subjectObjectAxis

theorem subjectObjectAxisRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (subjectObjectAxisRow G).ObeysSeparateFuse :=
  rowOf_obeys G .subjectObjectAxis

theorem subjectObjectAxisRow_not_freeze :
    ¬ (subjectObjectAxisRow G).Freeze :=
  rowOf_not_freeze G .subjectObjectAxis

theorem insentient_subject_collapse_self_refuting (t : Tier G) :
    ¬ (subjectObjectAxisRow G).Collapse t :=
  rowOf_collapse_self_refuting G .subjectObjectAxis t

abbrev undefinedZeroRow (G : Grid Contrib) : Distinction G :=
  rowOf G .undefinedZero

theorem undefinedZeroRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (undefinedZeroRow G).ObeysSeparateFuse :=
  rowOf_obeys G .undefinedZero

theorem undefinedZeroRow_not_freeze :
    ¬ (undefinedZeroRow G).Freeze :=
  rowOf_not_freeze G .undefinedZero

theorem undefined_as_openness_collapse_self_refuting (t : Tier G) :
    ¬ (undefinedZeroRow G).Collapse t :=
  rowOf_collapse_self_refuting G .undefinedZero t

abbrev perCallGlobalRow (G : Grid Contrib) : Distinction G :=
  rowOf G .perCallGlobal

theorem perCallGlobalRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (perCallGlobalRow G).ObeysSeparateFuse :=
  rowOf_obeys G .perCallGlobal

theorem perCallGlobalRow_not_freeze :
    ¬ (perCallGlobalRow G).Freeze :=
  rowOf_not_freeze G .perCallGlobal

theorem perCallGlobal_collapse_self_refuting (t : Tier G) :
    ¬ (perCallGlobalRow G).Collapse t :=
  rowOf_collapse_self_refuting G .perCallGlobal t

abbrev terminusExitRow (G : Grid Contrib) : Distinction G :=
  rowOf G .terminusExit

theorem terminusExitRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (terminusExitRow G).ObeysSeparateFuse :=
  rowOf_obeys G .terminusExit

theorem terminusExitRow_not_freeze :
    ¬ (terminusExitRow G).Freeze :=
  rowOf_not_freeze G .terminusExit

theorem exit_collapse_self_refuting (t : Tier G) :
    ¬ (terminusExitRow G).Collapse t :=
  rowOf_collapse_self_refuting G .terminusExit t

abbrev selfPoleTransposedRow (G : Grid Contrib) : Distinction G :=
  rowOf G .selfPoleTransposed

theorem selfPoleTransposedRow_obeys
    [∀ w : G.Weld, Decidable (AtBot (G.share w))] :
    (selfPoleTransposedRow G).ObeysSeparateFuse :=
  rowOf_obeys G .selfPoleTransposed

theorem selfPoleTransposedRow_not_freeze :
    ¬ (selfPoleTransposedRow G).Freeze :=
  rowOf_not_freeze G .selfPoleTransposed

theorem transposition_erased_downward_collapse_self_refuting (t : Tier G) :
    ¬ (selfPoleTransposedRow G).Collapse t :=
  rowOf_collapse_self_refuting G .selfPoleTransposed t

/-- Rows of the Grade-1 table that remain prose; their reasons are recorded in
    Identification/Commentary.lean and the paper commentary. -/
inductive ProseRow
  | beingNonBeing
  | ladderTerminus
  | genjoSho
  | shoSatori
  | row2Row3
  | descriptionInjunction

/-- A table row is schema-generated, ladder-generated, or prose. -/
inductive TableRow
  | generated (r : RowTag)
  | ladderSchema
  | prose (p : ProseRow)

def tableOrder : List TableRow := [
  .prose .beingNonBeing,
  .ladderSchema,
  .prose .ladderTerminus,
  .generated .rungPole,
  .prose .genjoSho,
  .prose .shoSatori,
  .generated .foxWeld,
  .prose .row2Row3,
  .generated .functionShare,
  .generated .karmaInga,
  .generated .sowingReaping,
  .generated .deliveryIndex,
  .generated .weldEventType,
  .generated .standingDated,
  .generated .subjectObjectAxis,
  .generated .undefinedZero,
  .generated .perCallGlobal,
  .prose .descriptionInjunction,
  .generated (.layer .gridLens),
  .generated .terminusExit,
  .generated .selfPoleTransposed,
  .generated (.layer .directedTime),
  .generated (.layer .beings) ]

example : tableOrder.length = 23 := rfl

end GridConvention
end BeingConvention
end DirectedConvention

end Grid

/-- In the clock model, share-zero does not mean function-zero: the adaptive
    clock answers the present-listener call at bottom share while remaining
    non-stone. -/
theorem shareZero_not_functionZero_witness :
    AtBot (clockGrid.share ⟨Clock.adaptive, Listener.present, Chime.chime⟩) ∧
      ¬ clockGrid.Stone Clock.adaptive :=
  ⟨clockGrid.atBot_of_terminus_response adaptive_is_terminus rfl,
    adaptive_not_stone⟩

/-- In the register clock, a live share-drop rung is not yet the pole. -/
theorem rung_not_pole_witness :
    ∃ before : Config Nat, ∃ received : registerClockGrid.Weld,
      registerClockGrid.Actual received ∧
        registerClockGrid.IsShareDrop before received ∧
        ¬ AtBot (registerClockGrid.share received) := by
  refine ⟨{ tendency := 5 }, ⟨(2 : Nat), (), (3 : Nat)⟩, ?_, ?_, ?_⟩
  · rfl
  · dsimp [Grid.IsShareDrop, Grid.share, registerClockGrid]
    constructor
    · show (2 : Nat) ≤ 5
      decide
    · show ¬ (5 : Nat) ≤ 2
      decide
  · dsimp [Grid.share, registerClockGrid, AtBot, shareBot]
    show ¬ (2 : Nat) ≤ 0
    decide

/-- Assertable and displayable are different verdict voices. -/
theorem assertable_ne_displayable :
    Grid.VerdictVoice.assertable ≠ Grid.VerdictVoice.displayable := by
  intro h
  cases h

/-- A standing tendency does not determine the dated reception: in the clock
    model a live prior tendency can re-pitch to a pole-class received share. -/
theorem standing_does_not_determine_dated :
    ∃ before : Config Nat, ∃ received : clockGrid.Weld,
      ¬ AtBot before.tendency ∧
        AtBot (clockGrid.rePitch before received).tendency := by
  refine ⟨{ tendency := 5 }, ⟨Clock.adaptive, Listener.present, Chime.chime⟩,
    ?_, ?_⟩
  · dsimp [AtBot, shareBot]
    show ¬ (5 : Nat) ≤ 0
    decide
  · exact clockGrid.rePitch_tendency_atBot_of_terminus_response
      { tendency := 5 } adaptive_is_terminus rfl

/-- The pole-validating act-time is inhabited by a non-stone terminus response
    in the clock model; the validating disjunct is not merely the vacuous stone
    side. -/
theorem pole_tier_buddha_inhabited :
    ∃ w : clockGrid.Weld,
      clockGrid.Actual w ∧ AtBot (clockGrid.share w) ∧
        clockGrid.AtPoleClass w.agent ∧ ¬ clockGrid.Stone w.agent := by
  refine ⟨⟨Clock.adaptive, Listener.present, Chime.chime⟩, rfl, ?_, ?_, ?_⟩
  · exact clockGrid.atBot_of_terminus_response adaptive_is_terminus rfl
  · exact clockGrid.atPoleClass_of_terminus Clock.adaptive adaptive_is_terminus
  · exact adaptive_not_stone


end WAA
